### ISSUE TITLE
Feature Request - Include dates of addon updates on the main screen.

### ISSUE THREAD

**Issue by MamboDead** [jliddev/WowUp#152]
Showing the date an update was released on the "My Addons" screen next to addons (or when hovering over the Latest Version)
With pre patch fiesta I've gotten some Addon updates from Discords directly, already lost Details by accidentally updating through the app.
Having a date in there when the update got released would be handy in cases like these.

**Comment by Accomp** [comment]
I came here to make the same request. A simple solution would be to change the "Latest Version" column to "Version" and add a new column for "Last Updated" with the timestamp of the latest version commit.

This would enable folks to sort by "Last Updated" to show the most recently updated addons at the top, rather than having to sort by "Status", then alphabetically as it functions today (particularly useful for those who have addons updating automatically).

**Comment by cgmartin** [comment]
Sorting by the dates of the addon release would be super helpful, especially now with Shadowlands where I am trying to figure out which Addons might need to be replaced due to inactive maintenance.

**Comment by CleverChrononaut** [comment]
I came here to make this exact feature request. With the release of Shadowlands, I have disabled all addons that were causing UI errors until they have been updated and it is difficult to determine which add-ons have been updated recently via WowUp, so this would be a very nice-to-have feature.

**Comment by jliddev** [comment]
This is implemented in 2.0
