### ISSUE TITLE
Possible problem with Classic. The addon cannot tell the difference between retail and classic versions of an addon.

### ISSUE THREAD

**Issue by dreamscape89** [jliddev/WowUp#175]
The following example:

- I already have installed ShadowedUnitFrames-v4.2.3-Classic-3-g4aeee73
- WoWUp prompts for an update while Twitch client does not.
- WoWUp shows that latest version is v4.3.2, which is the retail version of SUF not Classic.
- You can see the latest classic or retail versions here: https://www.curseforge.com/wow/addons/shadowed-unit-frames/files
- It seems WoWUp cannot tell the difference between classic and retail. 

Other examples : 

- I have : https://www.curseforge.com/wow/addons/gathermate2-classic/files
- WoWUp wants me to update to : https://www.wowinterface.com/downloads/info21293  which is for Retail not Classic.

- I have installed : https://www.curseforge.com/wow/addons/nugenergy/files/3004444
- WoWup wants me to update to : https://www.wowinterface.com/downloads/info9099 Again, it's retail version

I dont even have this addons installed for retail. In fact only did a fresh install of Retail today and got only two addons that are totally different.

WoW classic is selected and path is correct.
After using the Re-scan folder feature, some of them went away but some still persist.
You can see problematic addons if you update/install addons via Twitch client then they show up as update in WoWup.
The fact you have to use re-scan feature, this can be very problematic for someone who installs the app for the first time as they will mess their versions unknowingly if they do not pay attention and just update all.

Edit: The more I use the Re-Scan button, the more it changes some addons come back or new ones appear. That DO NOT need updating

![Untitled](https://user-images.githubusercontent.com/55486103/96464124-20071f80-1230-11eb-8e5a-8df3c7df6f39.png)

Note in the screen shot that SUF fixed but still asks for an update somehow. It used to want to update to retail version before.

**Comment by jliddev** [comment]
There's a lot of things at play here. Im guessing you're on version 1.18.4. The Curseforge API is broken right now and returning random results when trying to match, which in your first example ShadowedUnitFrames is probably causing it to be sourced from WowInterface dur to Curse sometimes not returning it. The Author does not make an distinction between retail and classic and puts the WowInterface ID of the retail one in the toc. WowInterface has no concept of classic vs retail so that is an issue but not a simple one to solve.  The rest are likely symptomatic of the same thing. 

I would recommend you try out the 2.0 alpha or the 1.19 beta as we had to create our own fingerprinting server for curse because theirs is completely broken, that should fix a lot of the issues you are seeing.
