### ISSUE TITLE
Unable to select an WoW installation path v.1.14.12.0

### ISSUE THREAD

**Issue by JoschiGrey** [jliddev/WowUp#35]
Clicking on "select" in the Welcome pls select your path screen does nothing.

**Comment by jliddev** [comment]
Strange that it would even ask. is your battle.net launcher up to date?

**Comment by vbarrancos** [comment]
Same issue here, clicking Select does nothing.  Battle.net is installed and is up-to-date, as is my WoW installation in the bnet launcher.

![image](https://user-images.githubusercontent.com/6812901/91672913-e1d66500-eaf6-11ea-8173-66519d0e1516.png)

If it's trying to autodetect it, it's possible that my WoW installation folder isn't specified in the registry or something because I usually just copy the whole folder over whenever I reinstall Windows.

**Comment by jliddev** [comment]
Hmm, either of you mind sending me your log file? WowUp uses the battle.net product file to know where you installed it at. so usually just making sure thats up to date works. I am aware that button is broken on this version and will patch it asap.

in explorer
%LOCALAPPDATA%\wowup

**Comment by JoschiGrey** [comment]
As I just realized Battle.Net lost the installation path itself, an update of WoW fixed the problem.

Sorry for the inconvenience.

**Comment by jliddev** [comment]
Closing as resolved
