### ISSUE TITLE
Installed  addons in "Get Addons"

### ISSUE THREAD

**Issue by panxoo90** [jliddev/WowUp#40]
When going to the tab  "Get Addons" if you see your adddon in the list the button "Install" shows up anyways. It should be disabled or something? I didnt try to install the adddon again because can mess up my UI , sorry.

**Comment by jliddev** [comment]
Ones you already have installed should not show up in the "Get Addons" tab.  Is there a way to cause this?

**Comment by MaximilianKresse** [comment]
This seems to be some kind of first startup error. I had the same problem and as I wanted to make some screenshoots of this error for you it disappeared 😅

**Comment by alexlemaire** [comment]
Got the same issue on my side. When you start the app for the first time, the _Get Addons_ tab will list all addons even if you have some of them installed. This gets fixed when you hit _Refresh_.

I'm assuming that the initial filtering in _Get Addons_ is performed before the folder scanning for installed addons is done and therefore it lets you install addons that you may already have.

Maybe waiting for the first folder scanning to be done before being able to get into _Get Addons_  would be a potential fix? Or swap around the steps so that the list of available addons is generated once the installed addons are all fetched?

**Comment by Shaydera** [comment]
This also happens after a  folder rescan if you installed addons manually or via different client.
Trying to install a already installed addon also throws an (handled) exception.
